# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./app
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
       dotnet-version: '6.0.x'
    - run: dotnet publish BlazorGitHubPagesDemo.csproj -c Release -o release --nologo
    
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        working-directory: ./release
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
